api:
   build: ./
   command: nodemon --watch api --watch database api/api.js
   links:
      - dbtest:db
      - broker
   ports:
      - "4000:4000"
   environment:
      - VIRTUAL_HOST=pheromon.ants.builders
      - VIRTUAL_PORT=4000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - NODE_ENV=test
      # Updater variables
      - UPDATER_RANGE_START=2200
      - UPDATER_RANGE_SIZE=10
      - UPDATER_PLAYBOOK_FOLDER="/pheromon/updateFiles/"
      - UPDATER_SENSORS_PORT=9632
   volumes:
      - ./:/pheromon
      # Ansible playbooks for the updater
      #- ./updateFiles/:/pheromon/updateFiles/:ro
      # SSH configuration
      #- /home/sensorSSH/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      #- /home/sensorSSH/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      #- /home/sensorSSH/.ssh/known_hosts:/root/.ssh/known_hosts
      #- /etc/ssh/ssh_config:/etc/ssh/ssh_config:ro
   tty: true
   log_driver: "none" 

broker:
   build: .
   command: nodemon --watch broker broker/index.js
   links:
      - dbtest:db
      - redis
   ports:
      - "5100:5100"
   environment:
      - VIRTUAL_PORT=5100
      - NODE_ENV=test
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon
   log_driver: "none" 

dbtest:
   image: postgres:9.4
   environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements # don't change the name of the variable for pg_dump
      - POSTGRES_PASSWORD=elements
   log_driver: "none" 

redis:
   image: redis:3
   log_driver: "none" 

tests:
   build: .
   command: node ./tests/index.js
   dockerfile: Dockerfile-test
   links:
      - api
      - broker
      - dbtest:db
   environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=elements # don't change the name of the variable for pg_dump
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon/
   tty: true
