api:
   build: ./
   command: nodemon api/api.js
   links:
      - db
      - broker
   ports:
      - "3900:3900"
   environment:
      - VIRTUAL_HOST=pheromon.ants.builders
      - VIRTUAL_PORT=3900
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elements
      - PGPASSWORD=elements
      - NODE_ENV=production
      # Updater variables
      - UPDATER_RANGE_START=2200
      - UPDATER_RANGE_SIZE=50
      - UPDATER_PLAYBOOK_FOLDER="/pheromon/updateFiles/"
      - UPDATER_SENSORS_PORT=9632

   volumes:
      - ./:/pheromon
      # Ansible playbooks for the updater
      - ./updateFiles/:/pheromon/updateFiles/:ro
      # SSH configuration
      - /home/sensorSSH/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - /home/sensorSSH/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - /home/sensorSSH/.ssh/known_hosts:/root/.ssh/known_hosts
      - /etc/ssh/ssh_config:/etc/ssh/ssh_config:ro
   tty: true
   restart: always

broker:
   build: .
   command: nodemon broker/index.js
   links:
      - db
      - redis
   ports:
      - "1883:1883"
   environment:
      - VIRTUAL_PORT=1883
      - NODE_ENV=production
      - POSTGRES_PASSWORD=elements
   volumes:
      - ./:/pheromon
   tty: true
   restart: always

db:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=elements
      - NODE_ENV=production
   volumes:
      - /data/pheromon/db:/var/lib/postgresql/data
   tty: true
   restart: always

redis:
   image: redis:3
   log_driver: "none" 
   restart: always
